ALTER TABLE  `users` CHANGE  `slug`  `slug` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE  `users` ADD  `first_name` VARCHAR( 30 ) NOT NULL AFTER  `password_token` , ADD  `last_name` VARCHAR( 30 ) NOT NULL AFTER  `first_name`;
ALTER TABLE  `tasks` CHANGE  `start_date`  `start_date` DATETIME NULL;
ALTER TABLE  `tasks` CHANGE  `end_date`  `end_date` DATETIME NULL;
ALTER TABLE  `tasks` CHANGE  `ordering`  `ordering` INT NOT NULL DEFAULT  '0';
ALTER TABLE  `tasklists` CHANGE  `ordering`  `ordering` INT NOT NULL DEFAULT  '0';
ALTER TABLE  `user_preference` CHANGE  `question_descriptions`  `question_description` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE  `user_preference` CHANGE  `type`  `code` VARCHAR( 25 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT  'g stands for global- this is saved in the users table';
ALTER TABLE  `user_preference` ADD  `type` VARCHAR( 25 ) NOT NULL AFTER  `code`;
UPDATE  `user_preference` SET  `type` =  'text' WHERE  `user_preference`.`id` =1;
UPDATE  `user_preference` SET  `type` =  'radio' WHERE  `user_preference`.`id` =2;
ALTER TABLE  `user_preference` ADD  `default` VARCHAR( 10 ) NOT NULL AFTER  `type`;
UPDATE  `user_preference` SET  `default` =  '20' WHERE  `user_preference`.`id` =1;
UPDATE  `user_preference` SET  `default` =  '1' WHERE  `user_preference`.`id` =2;